### PR TITLE
[iOS] Fix issue when `paymentToken` is not present on real iOS device.

### LINKED ISSUE #30: [iOS] paymentToken not present on real device
Yesterdays production deployment kinda surprised me. 

When testing in sandbox/production on device, `paymentToken` got lost. On simulator, it works perfectly.

Despite token arrives into JS ["accept" handler ](https://github.com/naoufal/react-native-payments/blob/master/packages/react-native-payments/lib/ios/ReactNativePayments.m#L323), it does pass [`_getPlatformDetailsIOS`](https://github.com/naoufal/react-native-payments/blob/5b45f79452009f7f48a6d3e762db885f47d67357/packages/react-native-payments/lib/js/PaymentRequest.js#L296)
The fact it works on simulator is an accident, present on [these lines](https://github.com/naoufal/react-native-payments/blob/5b45f79452009f7f48a6d3e762db885f47d67357/packages/react-native-payments/lib/js/PaymentRequest.js#L307)
```js
return Object.assign({}, details, {
    paymentData: null,
    serializedPaymentData
});
```
Calling `Object.assign` copies whatever is present in `details` object and passes it further.
Unfortunately, for real device, returned values are hand picked.

In both cases, return values should be hand picked to make sure they are equal in shape and/or values.

I am aware of #21 PR, I will try to build on that (unfortunately found the PR after my fix)

**Offtopic:**
Apple review passed, this lib is definitely safe for work!

### PR DESCRIPTION
**Pull request by Andreyco**
Other changes:
- this commit unifies responses for iOS simulator and real iOS device
- `serializedPaymentData` is no longer present. Data is always deserialised.
- add some Flow types and fix some (e.g `object` -> `Object`)

Fixes #30

### CODE REVIEW

File: packages/react-native-payments/lib/js/PaymentRequest.js [hunk 1]
```diff
@@ -287,41 +299,33 @@ export default class PaymentRequest {
...
       : this._getPlatformDetailsAndroid(details);
   }
 
-  _getPlatformDetailsIOS(details: {
-    transactionIdentifier: string,
-    paymentData: string
-  }) {
+  _getPlatformDetailsIOS(details: PaymentDetailsIOSRaw): PaymentDetailsIOS {
     const {
+      paymentData: serializedPaymentData,
```
Comment (naoufal) [inline packages/react-native-payments/lib/js/PaymentRequest.js]: Let's not refer to `serializedPaymentsData` as `paymentData` even we'll have a type for it --   It's likely to stump developers not using `flow`.

File: packages/react-native-payments/lib/js/PaymentRequest.js [hunk 2]
```diff
@@ -287,41 +299,33 @@ export default class PaymentRequest {
...
-    if (isSimulator) {
-      return Object.assign({}, details, {
-        paymentData: null,
-        serializedPaymentData
-      });
-    }
+    const isSimulator = transactionIdentifier === 'Simulated Identifier';
 
     return {
+      paymentData: isSimulator ? null : JSON.parse(serializedPaymentData),
```
Comment (naoufal) [inline packages/react-native-payments/lib/js/PaymentRequest.js]: I could see this stumping some people.  Could you update the README to warn users of the behaviour in TEST.

**Comment by Andreyco** [comment]
Sorry for being unresponsive in past days. Will take a look at those during this weekend. Appreciate your time here.

File: packages/react-native-payments/lib/js/PaymentRequest.js (hunk 1 above)
Comment (Andreyco) [reply packages/react-native-payments/lib/js/PaymentRequest.js]: Not sure I understand your advice here... Could you elaborate?

File: packages/react-native-payments/lib/js/PaymentRequest.js [hunk 3]
```diff
@@ -54,6 +54,18 @@ import {
   SUPPORTED_METHOD_NAME
 } from './constants';
 
+type PaymentDetailsIOS = {
```
[the remark this answers is not in the document]
Comment (Andreyco) [reply packages/react-native-payments/lib/js/PaymentRequest.js]: Done

File: packages/react-native-payments/lib/js/PaymentRequest.js (hunk 2 above)
Comment (Andreyco) [reply packages/react-native-payments/lib/js/PaymentRequest.js]: Sure, documentation is improved.

**Comment by campierce88** [comment]
any word on this pr?
